#!/usr/bin/env python3
"""Vendor Montserrat and Noto Sans locally.

Run by hand when the type system changes, not as part of `npm run build`:

    python3 tools/fetch-fonts.py

CLAUDE.md §3 allows either self-hosting or Google Fonts with display=swap.
Self-hosting wins here for two reasons. The stack rule in §2 says not to ship
third-party surveillance into a site serving a specific ethnic community, and a
Google Fonts stylesheet reports every visitor's IP and user agent to Google
before a word is drawn. It also removes a render-blocking request to a host
that is not ours, on pages read mostly over phone connections.

Only the latin subset is kept, and only the weights the stylesheets actually
use. The latin range already covers English, Tagalog, and the accented
characters this site prints — ñ, á, é, í, ó, ú all live there. latin-ext adds
Eastern European coverage for another 700 KB across the six faces, which is
most of a page budget spent on characters that never appear.
"""

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "src" / "assets" / "fonts"
CSS_OUT = ROOT / "src" / "styles" / "fonts.css"

# Montserrat 600/700 for card titles, headings, and the hero; Noto Sans
# 400/700 for body and bold. Every weight here is used — adding one that is not
# costs ~35 KB per family for nothing.
SOURCE = (
    "https://fonts.googleapis.com/css2"
    "?family=Montserrat:wght@600;700"
    "&family=Noto+Sans:wght@400;700"
    "&display=swap"
)

# A modern browser UA is required or Google serves the legacy TTF stylesheet.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

KEEP_SUBSETS = {"latin"}

HEADER = """/* Self-hosted webfonts. Generated by tools/fetch-fonts.py — edit that,
 * not this file.
 *
 * Two families total, per CLAUDE.md §2: Montserrat for headings, Noto Sans for
 * body. font-display: swap means text is readable in Arial before these land,
 * and if they never land the weight hierarchy still holds. */

"""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(SOURCE).decode("utf-8")

    blocks = []
    # Each @font-face is preceded by a /* subset */ comment naming its coverage.
    for subset, block in re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S):
        if subset not in KEEP_SUBSETS:
            continue

        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        remote = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
        path = FONT_DIR / name
        if not path.exists():
            path.write_bytes(fetch(remote))
        print(f"  {name:34s} {path.stat().st_size / 1024:6.1f} KB")

        blocks.append(
            block.replace(remote, f"/assets/fonts/{name}").replace("\n", "\n")
        )

    CSS_OUT.write_text(HEADER + "\n".join(blocks) + "\n")
    print(f"\nWrote {CSS_OUT.relative_to(ROOT)} with {len(blocks)} @font-face rules.")


if __name__ == "__main__":
    main()
